/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#101419",
        surface: "#101419",
        "surface-dim": "#101419",
        "surface-container": "#1d2025",
        "surface-container-low": "#191c21",
        "surface-container-high": "#272a30",
        "surface-container-highest": "#32353b",
        "surface-variant": "#32353b",
        "surface-bright": "#36393f",
        "on-surface": "#e1e2e9",
        "on-surface-variant": "#c1c7d3",
        "on-background": "#e1e2e9",
        "outline-variant": "#414751",
        outline: "#8b919d",
        primary: "#a4c9ff",
        "primary-container": "#60a5fa",
        "on-primary-container": "#003a6b",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        tertiary: "#ffb3ad",
        error: "#ffb4ab",
        "surface-tint": "#a4c9ff",
        slate: {
          card: "#1e293b",
          border: "#334155",
          inset: "#0f172a",
          row: "#141b26",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "data-display": ["20px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "data-label": ["12px", { lineHeight: "1.2", fontWeight: "400" }],
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "16px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
